# Generated by Django 2.2.5 on 2019-09-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afficheur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.IntegerField(default=10),
        ),
    ]
