# Generated by Django 2.2.5 on 2019-11-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afficheur', '0002_city_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'resumes'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='description',
        ),
        migrations.AddField(
            model_name='city',
            name='email',
            field=models.CharField(max_length=1000000000, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='phone',
            field=models.CharField(max_length=1000000000, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='skills',
            field=models.CharField(max_length=1000000000, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='url',
            field=models.CharField(max_length=1000000000, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=1000000000, null=True),
        ),
    ]
