# Generated by Django 2.2.5 on 2019-11-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0003_auto_20191123_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='raw',
            field=models.CharField(max_length=1000000000, null=True),
        ),
    ]
