# Generated by Django 2.2.5 on 2019-11-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0004_city_raw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='email',
        ),
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
        migrations.RemoveField(
            model_name='city',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='city',
            name='raw',
        ),
        migrations.RemoveField(
            model_name='city',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='city',
            name='url',
        ),
        migrations.AddField(
            model_name='city',
            name='search',
            field=models.CharField(max_length=1000000000, null=True),
        ),
    ]
